Add attribute good rolls
hannibal002/SkyHanni-REPO pull request #222
Opened 2024-06-28 16:04 UTC by ItsEmpa

needed for hannibal002/SkyHanni#2001

2024-06-28 18:32 UTC, jani270 requested changes
This has been formatted with 4 Spaces instead of 2 Spaces

2024-06-28 18:53 UTC, jani270 approved these changes

2024-08-11 20:31 UTC, hannibal002 requested changes
Please rename the json file to AttributeGodRolls, AttributeGoodRolls, or something similar

2024-10-09 09:18 UTC, CalMWolfs approved these changes

2024-10-11 18:35 UTC, hannibal002 requested changes
Settings and logic look fine, feature worked fine while testing ingame.
but please use an abstract attribute class instead of an enum, so that we can fully change it via repo

2024-10-22 18:39 UTC, merged