Add personal best increments
hannibal002/SkyHanni-REPO pull request #295
Opened 2024-11-26 18:19 UTC by Chissl

Adds max personal bests for crops in jacob contests

2024-11-26 18:24 UTC, lunaynx requested changes
The values should probably just be integers, I can't ever see a case where you could get a fractional amount of collection.

2024-11-26 18:24 UTC, lunaynx commented on constants/Garden.json
> +    "COCOA_BEAN": 3000000.0,
```suggestion
    "COCOA_BEANS": 3000000.0,
```
`CropType` uses `COCOA_BEANS`.

2024-11-27 00:39 UTC, ptlthg commented
What's the use case for this? You can get higher PB scores than these (even if the fortune stops counting here). I think it'd be better to just calculate these numbers when needed by using the collection per PB fortune * 100

2024-11-28 08:39 UTC, CalMWolfs approved these changes

2024-11-28 23:30 UTC, merged