Maxwell powers and arrow data for scoreboard
hannibal002/SkyHanni-REPO pull request #92
Opened 2024-01-08 17:24 UTC by j10a1n15

Added ArrowType & Maxwell Powers to Repo
Needed for [#893](https://github.com/hannibal002/SkyHanni/pull/893)

2024-01-08 18:07 UTC, Thunderblade73 requested changes
Please make "arrow" the key of the object. To make it more consistent with the rest of the repo files.

2024-01-08 19:04 UTC, j10a1n15 commented
done

2024-01-08 19:07 UTC, Thunderblade73 commented
Ehm, not really what I have meant. I said the value "arrow" should be the key of the object. Example:
"None" : {
"internal Name" : "None" 
}

2024-01-08 19:17 UTC, j10a1n15 commented
ooh like that

2024-01-08 19:18 UTC, j10a1n15 commented
In my code I use both values tho, and its easier with the way I have it right now

2024-01-08 19:19 UTC, Thunderblade73 commented
The values you get stay the same, only the format as a json needs to change. (And the parser)

2024-01-08 19:51 UTC, j10a1n15 commented
lmao

2024-01-08 19:52 UTC, j10a1n15 commented
I dont wanna talk about that

2024-01-08 20:24 UTC, j10a1n15 commented
done part 2

2024-01-08 20:33 UTC, Thunderblade73 approved these changes
Looks fine

2024-01-08 20:39 UTC, j10a1n15 commented
Im sorry but I think Ill have to revert that because the parser just got like bad and idk how to even do that

2024-01-09 10:45 UTC, Thunderblade73 commented
Ehm, did you test the code, because in your branch the json File is called "ArrowTypes" but here it is called "ArrowType". Please change the file name to "ArrowTypes".
Also I wrote you the parser (opened a PR for it), if you want to use the other format. Also in the other format was an error because it needs an object open instead of an arrow opened when using a map. E.g; "[]" to "{}". 
```
{
"arrows":{
...
}
}
```
instead of:
```
{
"arrows":[
...
]
}
```

2024-01-09 10:53 UTC, j10a1n15 commented
I can't test it bc im banned lol
But thank you will look at it later

2024-01-09 10:57 UTC, Thunderblade73 commented
True, I remember now.😅

2024-01-09 13:57 UTC, hannibal002 commented
> I can't test it bc im banned lol

lets make a command that works on singleplayer only /thisisskyblock <island> to test stuff while bannned

2024-01-13 03:17 UTC, CalMWolfs approved these changes
format looks good

2024-01-13 19:58 UTC, hannibal002 requested changes

2024-01-13 19:58 UTC, hannibal002 commented on constants/ArrowTypes.json
What else do we want to save in this file in the future? If nothing else, please use `a -> b` instead of `a: {arrow: b}`

2024-01-13 20:00 UTC, j10a1n15 commented on constants/ArrowTypes.json
Maybe in the future we might need strength number idk

2024-01-13 20:01 UTC, merged